#datetime
import datetime

x = datetime.datetime.now()
print(x)
print(x.year)
print(x.strftime('%A'))

x = datetime.datetime(2020,5,17)
print(x)

x = datetime.datetime.now()
print("Month Name: ", x.strftime("%B")) 
print("Weekday: ", x.strftime("%a"))
print("Weekday number: ", x.strftime("%w"))
print("DayOfMonth: ", x.strftime("%d"))
print("Month name short: " , x.strftime("%b"))
print("Month name full: ", x.strftime("%B"))
print("Month number: ", x.strftime("%m"))
print("Year short: ", x.strftime("%y"))
print("Year full: ", x.strftime("%Y"))
print("Hour 24 format: ", x.strftime("%H"))
print("Hour 12 format: ", x.strftime("%I"))
print("AMPM: ", x.strftime("%p"))
print("Minute: ", x.strftime("%M"))
print("Second: ", x.strftime("%S"))
print("MicroSecond: ", x.strftime("%f"))
print("UTC offset: ", x.strftime("%z"))
print("Timezone: ", x.strftime("%Z"))
print("Day number: ", x.strftime("%j"))
print("Week number of year, sunday frist day: ", x.strftime("%U"))
print("Week number of year, monday frist day: ", x.strftime("%W"))
print("Local version of datetime: ", x.strftime("%c"))
print("Century: ", x.strftime("%C"))
print("Local version of date: ", x.strftime("%x"))
print("Local version of time: ", x.strftime("%X"))
print("ISO 8601 year: ", x.strftime("%G"))
print("ISO 8601 weekday: ", x.strftime("%u"))
print("ISO 8601 weeknumber: ", x.strftime("%V"))

