# numpy array search
import numpy as np

print('search 1-D array')
arr = np.array([1,2,3,4,5,64,4,7,4])
x = np.where(arr == 4)
print(x)
print('indexes where numbers are even')
x = np.where(arr%2 == 0)
print(x)
print('indexes where numbers are odd')
x = np.where(arr%2 == 1)
print(x)
print('searchsorted on sorted array')
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)
x = np.searchsorted(arr,10)
print(x)
x = np.searchsorted(arr, 5)
print(x)
x = np.searchsorted(arr,7,side='right')
print(x)
x = np.searchsorted(arr,10,side='right')
print(x)
x = np.searchsorted(arr, 5, side='right')
print(x)
print('multiple search')
arr = np.array([1,2,3,3,4,5,8,8,63])
x = np.searchsorted(arr,[3,63,8])
print(x)